[run]
workdir = "/checkpoint/metaspeechssl/mahiluthra"
wandb_mode = "offline"
wandb_project = "spidr_adapt_codebase"
wandb_name = "spidr_test_compile"
model_type = "spidr"

[data]
manifest = "/datasets/metaspeechssl/mahiluthra/split_vad_audio_vp20/vox19_train.csv"

[validation]
english.manifest = "/datasets/metaspeechssl/shared/assets/manifests/voxpopuli/finetuning/english/finetuning-dev-vadcut.csv"
